package com.example.livescoresdu.uilibrary.values

const val LOGIN_ROUTE = "login_route"
const val MAIN_ROUTE = "main_route"
const val PROFILE_ROUTE = "profile_route"
const val CHAT_ROUTE = "chat_route"
const val MORE_ROUTE = "more_route"
const val CARD_ROUTE = "card_route"
const val REFERENCES_ROUTE = "references_route"
const val CARD_ROUTE_ARGS = "card_route/{card_id}"
const val ACCOUNT_ROUTE = "account_route"
const val ACCOUNT_ROUTE_ARGS = "account_route/{account_number}"
const val DEPOSIT_ROUTE = "deposit_route"
const val DEPOSIT_ROUTE_ARGS = "deposit_route/{deposit_number}"
const val PAYMENTS_ROUTE = "payments_route"
const val TRANSFERS_ROUTE = "transfers_route"
const val CHILD_CARD_ROUTE = "child_card_route"
const val CHILD_CARD_ROUTE_ARGS = "child_card_route/{child_card_number}"
const val STORIES_ROUTE = "stories_route"
const val FOREX_ROUTE = "forex_route"
const val ACTIVES_ROUTE = "actives_route"
const val CREDITS_ROUTE = "credits_route"
const val CREDITS_ROUTE_ARGS = "credits_route/{credit_number}"
const val GOVERNMENT_ROUTE = "government_route"
const val INSURANCE_ROUTE = "insurance_route"
const val INSURANCE_ROUTE_ARGS = "insurance_route/{insurance_number}"
const val HISTORY_OPERATION_ROUTE = "history_operation_route"
const val CASHBACK_ROUTE = "cashback_route"
